[pytest]
asyncio_mode = auto
testpaths = tests
pythonpath = . ..

# test_app を無視するように python_functions を明示的に制限する
python_files = test_*.py
python_classes = Test*
python_functions = test_* !test_app

# 外部ライブラリ由来の DeprecationWarning などを非表示にする
filterwarnings =
    ignore::pytest.PytestCollectionWarning
    ignore::DeprecationWarning:starlette.*